# Generated by Django 3.0.5 on 2020-04-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200429_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='publish_date',
        ),
    ]
