# Generated by Django 3.0.5 on 2020-04-29 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200429_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 7, 58, 12, 15119)),
        ),
    ]
